spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tradingdb
    username: tradingdb
    password: tradingdb
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8081

grpc:
  server:
    port: 9094
  client:
    user_service:
      address: static://localhost:9091
      negotiationType: plaintext

logging:
  level:
    org:
      springframework:
        web: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
